"""empty message

Revision ID: 228527a2db25
Revises: f04db31e8114
Create Date: 2025-03-01 23:49:50.355595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228527a2db25'
down_revision = 'f04db31e8114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
