"""empty message

Revision ID: 6fc3e88a2a16
Revises: af21a4af918b
Create Date: 2025-02-28 12:41:31.355918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc3e88a2a16'
down_revision = 'af21a4af918b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_integrity_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('contact_integrity_hash', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('contact_integrity_hash')
        batch_op.drop_column('address_integrity_hash')

    # ### end Alembic commands ###
