"""empty message

Revision ID: 745e240bd7b0
Revises: 0d4c6acbedda
Create Date: 2025-03-01 19:28:36.056466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745e240bd7b0'
down_revision = '0d4c6acbedda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('private_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('public_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('public_key')
        batch_op.drop_column('private_key')

    # ### end Alembic commands ###
