"""empty message

Revision ID: 89d65c5aabf5
Revises: 745e240bd7b0
Create Date: 2025-03-01 20:50:20.878560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89d65c5aabf5'
down_revision = '745e240bd7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('address_integrity_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('contact_integrity_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('contact_integrity_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('address_integrity_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
