"""empty message

Revision ID: a6c376058b10
Revises: 88f161128d77
Create Date: 2025-02-27 06:00:52.275523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6c376058b10'
down_revision = '88f161128d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Text(), nullable=True))
        batch_op.drop_column('Contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Contact', mysql.TEXT(), nullable=True))
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
