"""empty message

Revision ID: af21a4af918b
Revises: a6c376058b10
Create Date: 2025-02-27 06:12:54.501566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af21a4af918b'
down_revision = 'a6c376058b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.Text(), nullable=True))
        batch_op.drop_column('Contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Contact', mysql.TEXT(), nullable=True))
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
