"""empty message

Revision ID: f04db31e8114
Revises: 89d65c5aabf5
Create Date: 2025-03-01 21:19:18.955335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f04db31e8114'
down_revision = '89d65c5aabf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('signature',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
